### ISSUE TITLE
Fix /boot and /lib/module handling

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/kubeadm-dind-cluster#1]
As of now, `/boot` and `/lib/modules` are not copied from the host and we don't mount them with `-v` either because this is not compatible with Moby Linux-based Dockers (e.g. Mac OS X). The proper solution to this is copying these directories from the host Linux by means of e.g. busybox image + nsenter. This is needed for Virtlet to work on kubeadm-dind-cluster.

**Comment by ivan4th** [comment]
For /modules: fixed
For /boot: no need for this now (e.g. Virtlet works without it)

**Comment by idvoretskyi** [comment]
> For /modules: fixed
@ivan4th can you refer the PR that fixes it?

**Comment by ivan4th** [comment]
The final fix is in 99f610e70abf05dd718639bbd1843b28a7ceec39 Unfortunately there's no PRs at the moment as no one except me is maintaining this project for now.
