### ISSUE TITLE
Consider adding a developer workflow example

### ISSUE THREAD

**Issue by castrojo** [Mirantis/kubeadm-dind-cluster#11]
Hello! I think people would see the obvious benefit of your approach if you documented what a workflow for using kubeadm-dind-cluster would look like for a kubernetes core developer. As an example:

1. Someone asks "hey check out my PR!" 
2. you `git pull foo`
3. Fire up the cluster with this branch.
4. You find a bug, fix it.
5. Restart the cluster to test.

It appears to me that steps 3-5 are very well suited to kubeadm-dind-cluster and probably much faster than using a VM, I think by giving people an example like this they can see how it would work first hand.

**Comment by ivan4th** [comment]
Thanks @castrojo, will update the docs.

**Comment by lukaszo** [comment]
Doc is available here https://github.com/Mirantis/kubeadm-dind-cluster#using-with-kubernetes-source
