### ISSUE TITLE
dind-cluster.sh script sometimes fails to detect moby Linux

### ISSUE THREAD

**Issue by luafran** [Mirantis/kubeadm-dind-cluster#15]
The reason is a race condition in the docker info and grep -q pipe-line used as detection mechanism.

This is the detection mechanism used to detect moby Linux:

if docker info|grep -q '^Kernel Version: .*-moby$'; then
    is_moby_linux=1
fi

Since _grep -q_ exits immediately with a zero status as soon as a match is found, sometimes it exists while _docker info_ is still writing to the pipe, but there is no reader (because grep has exited), so _docker info_ receives a _SIGPIPE_ signal from the kernel and it exits with a status of 141.
Now, given that _pipefail_ shell option is enabled, the pipe-line's return status is the value of the last (rightmost) command to exit with a non-zero status, that is, docker info exit status equal to 141, hence, the if condition is not true in these cases.

**Comment by ivan4th** [comment]
Fixed by #16
