### ISSUE TITLE
Fixes to run on OSX

### ISSUE THREAD

**Issue by zoobab** [Mirantis/kubeadm-dind-cluster#18]
Hi,

I made a kubernetes workshop, and some people made a fix to run kubeadm-dind on OSX:

https://www.meetup.com/Docker-Belgium/events/240356311/comments/480799431/?read=1&_af=event&_af_eid=240356311&itemTypeToken=COMMENT&https=on

"one1zero1one
Done also in OSX 10.11.6, had to do the following: brew install md5shasum, created a /boot folder in OSX and added it to docker preferences file sharing, then did a chmod a+x kubectl-v1.6.1 in the /Uses/user/.kubeadm-dind­-cluster - after that the script runs fine and you get teh cluster." 

I don't have OSX myself, but I am gonna try to reproduce it via a vagrant OSX box using KVM and nested virtualization.

I think he used Docker-on-mac.

**Comment by ivan4th** [comment]
Thanks for info, will try to make this easier. I have lots of GNU tools installed via brew on my Mac and didn't find out some easy way to have some "clean" mac env to test the scripts. (As for Linux, everything is tested on Travis, but Mac OS X is non-free there)

**Comment by djschny** [comment]
Closed with https://github.com/Mirantis/kubeadm-dind-cluster/pull/20 ?

**Comment by tiefpunkt** [comment]
@djschny @ivan4th the `chmod ~/.kubeadm-dind-cluster/kubectl-*` is still necessary, so I don't think this has really been fixed fully.

**Comment by redr0bin** [comment]
Sorry for commenting in already closed ticket, but are there any docker / macOS version requirements to run dind-cluster locally ?
