### ISSUE TITLE
Error starting daemon: error initializing graphdriver: driver not supported

### ISSUE THREAD

**Issue by danehans** [Mirantis/kubeadm-dind-cluster#23]
I am unable to deploy a kubeadm-dind-cluster on Ubuntu 16.04.2 or CentOS 7. I get the following error:

```
Jun 22 19:23:34 kube-master systemd[1]: Starting Docker Application Container Engine...
Jun 22 19:23:34 kube-master rundocker[180]: Trying to load overlay module (this may fail)
Jun 22 19:23:34 kube-master rundocker[180]: time="2017-06-22T19:23:34.197080260Z" level=info msg="libcontainerd: new containerd process, pid: 189"
Jun 22 19:23:35 kube-master rundocker[180]: time="2017-06-22T19:23:35.208001616Z" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"
Jun 22 19:23:35 kube-master systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jun 22 19:23:35 kube-master systemd[1]: Failed to start Docker Application Container Engine.
Jun 22 19:23:35 kube-master systemd[1]: docker.service: Unit entered failed state.
Jun 22 19:23:35 kube-master systemd[1]: docker.service: Failed with result 'exit-code'.
```

Here are details of my CentOS 7 setup:
```
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

$ rpm --query centos-release
centos-release-7-3.1611.el7.centos.x86_64

# docker info|grep Storage
Storage Driver: overlay
```

I have tried the overlay and overlay2 drivers, but I hit the same error.

Here are the details of my Ubuntu setup:
```
# cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

# docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

# docker info | grep Stor
WARNING: No swap limit support
Storage Driver: aufs
```
@pmichali is experiencing the same problem.

We are trying to use kubeadm-dind-cluster for k8s IPv6 e2e testing. More details on the issue can be found at https://github.com/kubernetes/kubernetes/issues/47666

**Comment by pmichali** [comment]
I'm seeing this same thing on centOS 7.3.1611 as well. Using Docker 17.06.0-ce (and have tried 1.12.6 too), kernel 3.10, and have storage driver set to devicemapper. The kubeadm init step fails, with log saying graphdriver not supported.

I have tried removing /var/lib/docker and made sure that when things start up, there is only a devicemapper directory (only one driver area).

I have tried adding /etc/docker/daemon.json specifying overlay, overlay2, and devicemapper, with the same results.

I'm wondering if the graphdriver is a red herring, and there is a different failure causing the docker service to fail?

I did, BTW, run "kubeadm init" from the command line (I know, not using ontainers), and it starts up fine.

Lastly, I tried this on a Vagrant created VM running CentOS 7 and see the same issue.

Any suggestions?

**Comment by ivan4th** [comment]
@danehans @pmichali Can you point me to some public vagrant image that exhibits this behavior? https://app.vagrantup.com/centos/boxes/7 is affected perhaps, right?

**Comment by pmichali** [comment]
In the journalctl log, I see:

```
Jul 06 15:10:22 devstack-77 systemd[1]: kubelet.service holdoff time over, scheduling restart.
Jul 06 15:10:22 devstack-77 systemd[1]: Started kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has finished starting up.
--
-- The start-up result is done.
Jul 06 15:10:22 devstack-77 systemd[1]: Starting kubelet: The Kubernetes Node Agent...
-- Subject: Unit kubelet.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kubelet.service has begun starting up.
Jul 06 15:10:22 devstack-77 kubelet[7423]: I0706 15:10:22.387258    7423 feature_gate.go:144] feature gates: map[]
Jul 06 15:10:22 devstack-77 kubelet[7423]: error: failed to run Kubelet: invalid kubeconfig: stat /etc/kubernetes/kubelet.conf: no such file or directory
Jul 06 15:10:22 devstack-77 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Jul 06 15:10:22 devstack-77 systemd[1]: Unit kubelet.service entered failed state.
Jul 06 15:10:22 devstack-77 systemd[1]: kubelet.service failed.
```

**Comment by pmichali** [comment]
@ivan4th Yeah, I have a Vagrant setup that uses this box: centos/7

**Comment by pmichali** [comment]
I have a Ubuntu 16.04 system in lab (behind firewall), and I tried a bunch of attempts there. It is using aufs for storage. I installed the extras package, and I **think**, I got past the init problem, but then hit a timeout error, trying to access a URL:
```
unable to get URL "https://storage.googleapis.com/kubernetes-release/release/stable-1.6.txt": Get https://storage.googleapis.com/kubernetes-release/release/stable-1.6.txt: dial tcp 172.217.7.144:443: i/o timeout
*** kubeadm failed
```

I'm wondering if the firewall is blocking this access, and not sure how to override (I guess it is running in a container? Normally, would set HTTP_PROXY and HTTPS_PROXY, like on host).  Is there a way to pass in environment variables to the container?

In any case, I'm trying another Vagrant VM, but using Ubuntu 16.04, to see if it is a CentOS issue (combined with a FW issue in the lab).

**Comment by ivan4th** [comment]
The above URL unreachability is kubeadm problem, it apparently insists on trying to access release info even if it's installing k8s using prebuilt hyperkube image. It's possible to pass proxy settings but you'll need to add args like `-e HTTP_PROXY="${HTTP_PROXY:-}" -e HTTPS_PROXY="${HTTPS_PROXY:-}" \` around this place in the script https://github.com/Mirantis/kubeadm-dind-cluster/blob/d85c415ed9f2689bacb668ff31729cd67a065b14/dind-cluster.sh#L435 -- try it and see if it helps.

As of centos/7 vagrant box, will check it shortly.

**Comment by pmichali** [comment]
@ivan4th Thanks!

I just tried Ubuntu 16.04 server, with docker version 17.06.0-ce, and using aufs storage driver, in a Vagrant based VM that I had.  Everything came up OK. I can't seem to get access to the dashboard (did port forwarding of TCP 8080), but could not access from host).

So, it looks like Ubuntu works (barring proxy issues - I'll try your suggestion). CentOS, OTOH, seems to be having some problems - not sure what exactly is preventing cluster from coming up.

**Comment by danehans** [comment]
@pmichali I think I'm at the same place as you know. The dind deploy is almost 100% working. The dashboard deployment hangs:
```
* Bringing up kube-dns and kubernetes-dashboard 
deployment "kube-dns" scaled
deployment "kubernetes-dashboard" scaled
........................................<SNIP>

Looks like an issue with dashboard deployment:
```kubectl get deployment --namespace=kube-system
NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-dns               1         1         1            1           25m
kubernetes-dashboard   1         1         1            0           25m

kubectl describe deployment kubernetes-dashboard --namespace=kube-system
Name:			kubernetes-dashboard
Namespace:		kube-system
CreationTimestamp:	Thu, 06 Jul 2017 11:35:31 -0700
Labels:			app=kubernetes-dashboard
Annotations:		deployment.kubernetes.io/revision=1
Selector:		app=kubernetes-dashboard
Replicas:		1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
Pod Template:
  Labels:	app=kubernetes-dashboard
  Annotations:	scheduler.alpha.kubernetes.io/tolerations=[
  {
    "key": "dedicated",
    "operator": "Equal",
    "value": "master",
    "effect": "NoSchedule"
  }
]

  Containers:
   kubernetes-dashboard:
    Image:		gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0
    Port:		9090/TCP
    Liveness:		http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:	<none>
    Mounts:		<none>
  Volumes:		<none>
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	True	MinimumReplicasAvailable
OldReplicaSets:	<none>
NewReplicaSet:	kubernetes-dashboard-2396447444 (1/1 replicas created)
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  25m		25m		1	deployment-controller			Normal		ScalingReplicaSet	Scaled up replica set kubernetes-dashboard-2396447444 to 1
  25m		25m		1	deployment-controller			Normal		ScalingReplicaSet	Scaled down replica set kubernetes-dashboard-2396447444 to 0
  23m		23m		1	deployment-controller			Normal		ScalingReplicaSet	Scaled up replica set kubernetes-dashboard-2396447444 to 1
```

**Comment by pmichali** [comment]
@danehans On mine, I think the dashboard is up (as I can curl to it from the VM. I just can't seem to access via browser on host (not sure if the fact that I'm on VPN is interfering).

**Comment by pmichali** [comment]
@ivan4th The proxy settings are seen inside the container, but I cannot ping the proxy server from inside the container. I tried using IP address, instead of name, but no go. There is a default route, but I cannot ping the proxy from inside the container. Any ideas?

**Comment by danehans** [comment]
@pmichali can you post the output of `kubectl get po,svc,deploy --namespace=kube-system`

**Comment by danehans** [comment]
Looks like i'm having issues pulling the dashboard image from my lab for some reason. I don't see the image pull issue on my DockerforMac setup.

**Comment by pmichali** [comment]
@danehans On the Ubuntu in VM or BM?

**Comment by pmichali** [comment]
So looks like I have this status currently:

Ubuntu 16.04 VM - Works, but I cannot access the dashboard from host.

Ubuntu 16.04 Bare Metal - It is hung waiting for cluster to come up. Have proxy settings inside container, can ping proxy server from inside container, but apiserver container (from inside the container), has exited. No log that I can find.

CoreOS 7 VM and BM - See failure on first kubeadm init processing, saying that graphdriver not supported (using devicemapper). Not sure of the underlying problem.

@ivan4th any ideas on what to try/check in these failing cases?

**Comment by danehans** [comment]
@pmichali Ubuntu BM.

**Comment by pmichali** [comment]
@danehans I don't have it starting up under BM. At kubeadm init, it hangs trying to access external URL. I added in config options to cause the container to setup proxy server. From the container, I can see the proxy settings, ping the proxy server, but the process is still stuck.

I see (from inside the container), the apiserver container has exited (scheduler and controller are running). I don't see any logs, so I don't know why it has failed. I'm guessing it is still something with us being behind a firewall.

**Comment by pmichali** [comment]
@ivan4th Under CentOS, I see that it fails at kubeadm init, saying graphdriver: driver not supported. In looking into the container, I see that docker is not running. If I try to start it, it fails with the same error that is reported on the host.

Comparing this to Ubuntu, the container for Ubuntu is running Ubuntu, and the config file 10-dind.conf is calling out a storage driver of vfs. The actual driver is overlay2 inside the container (aufs on the host).  For CentOS, it has the same config in 10-dind.conf, but I'm not sure what driver it is actually trying to use. The container OS is RHEL 4.8.5-11.

Is there a way to check the driver being used? Is there a way to force it to something different?

**Comment by pmichali** [comment]
Also, for CentOS, the host (outer VM) is using devicemapper, which I read Docker says is the **only** supported driver for CentOS.

**Comment by pmichali** [comment]
More info for CentOS. Looks like it is trying to use overlay2, as I tried to set the device in a config file, and got this error:

```
Jul 07 17:44:19 kube-master rundocker[432]: time="2017-07-07T17:44:19Z" level=fatal msg="unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are speci
fied both as a flag and in the configuration file: storage-driver: (from flag: overlay2, from file: devicemapper)\n"
```

I don't see where that is set on the command line. Not sure if it is supported for RHEL 4.8.5. I see that for Fedora, devicemapper is supported, and overlay2 (Fedora 26 or later, experimental), or overlay (experimental). Not sure how that maps to RHEL 4.8.5 (or if I'm chasing my tail).

**Comment by pmichali** [comment]
Ref: https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#docker-ee-and-cs-engine

**Comment by pmichali** [comment]
So, with CentOS in VM and bare-metal, I have the issue with kubeadm failing, giving a storage driver error.

With Ubuntu on bare-metal, behind firewall, I can get past the kubeadm init storage driver issue, but then apiserver fails to start up (container keeps restarting). The kubelet service shows that it cannot communicate with the api server, and sync fails. Not sure why.

Any thoughts on how to debug this issue?

**Comment by pmichali** [comment]
@ivan4th Have some success with Ubuntu 16.04 in a lab that is behind a firewall. On the host, I have a http-proxy.conf file with proxy information for docker (in /etc/systemd/system/docker.service.d/. I modified dind-cluster-v1.6.sh to pass in the proxy environment variables to the master container as you mentioned. This allowed the master container to come up.

Inside of the master container, I was then seeing that the apiserver container was not coming up. It was failing to pull images from external repos.  I hacked the master container to add the same docker proxy settings in an http-proxy.conf file (like I did on the host), and then restarted docker. This now come up.

Do you have any ideas on how we can "inject" into the master container (and into the containers that get started for the master and minion kubeadm nodes) the proxy and no-proxy settings?

We're close to getting this working on a system behind a firewall.

**Comment by danehans** [comment]
@pmichali I was thinking of closing this since we resolved the original issue. If you want to continue to pursue the proxy issue, can you open a separate issue?

**Comment by pmichali** [comment]
@danehans OK. There are two issues. One is working behind a FW, the other is getting DinD to work on CentOS 7.

**Comment by danehans** [comment]
OK. I'm closing this issue since the original problem has been resolved. Thanks!
