### ISSUE TITLE
Enhancements for gce-setup.sh and error in dind-cluster.sh

### ISSUE THREAD

**Issue by pmichali** [Mirantis/kubeadm-dind-cluster#30]
To allow DinD to be easily used by developers at different locations, it would be nice to be able to specify the "zone" or have it read it in via config settings (like project is set).

May also want to allow the VM name to be overridden, so that the same script could be used from multiple machines. 

In dind_cluster.sh, when E2E command is performed, it ends up running e2e.go and passing -check_version_skew, which appears to have been renamed to -check-version-skew.

If wanted, I could do a pull request with these changes.

**Comment by pmichali** [comment]
Did a PR for some changes. Two tests failed. How do I retest, without pushing a new patch?

Do the tests setup GCE prior to the run, such that "zone" is defined, or do we need to handle the case where zone may not be configured in gcloud config?

Who should be assigned to this issue to review?

**Comment by pigmej** [comment]
@pmichali you can't recheck using our CI without pushing new patchset. Or you're trying to do it on your local machine?

Travis needs to fetch your code. To fetch it you need to push code :)

**Comment by pmichali** [comment]
@pigmej thanks. I did PR #31 to address the issue. It failed on one test, and I'm not sure why (so wanted to recheck).  Any thoughts about the zone question? I'm wondering if I need to check to see if config is empty and then hard code a zone as a last resort.

**Comment by pmichali** [comment]
@pigmej Can you help with test issues? I created PR #35, which has just one simple change from this PR that doesn't affect DinD operation (the original patch for this commit too, did not affect the tests), and it is failing src-1.7 and src-master tests. Looks like there is an issue with the baseline tests for these two.

I've got several commits (this one enhancing GCE, and fixing arg for dind-cluster.sh script; PR #35 that fixes a test setup step, when running locally; and an upcoming patch that will provide IPv6 support).

**Comment by lukaszo** [comment]
@pmichali did you fix all issues here?

**Comment by pmichali** [comment]
Yes, AFAIK.
