### ISSUE TITLE
init fails when run in systemd

### ISSUE THREAD

**Issue by lacek** [Mirantis/kubeadm-dind-cluster#318]
When`dind-cluster.sh init` is run in a systemd unit, the log shows:
```
...
tee: /dev/fd/2: No such device or address
...
*** kubeadm failed
```

The 2 errors are from https://github.com/kubernetes-sigs/kubeadm-dind-cluster/blob/814d9ca036b23adce9e6c683da532e8037820119/dind-cluster.sh#L1081-L1082

The `wrapkubeadm` in fact completed without error, but tee failed and led the script to stop.
I got it work around after removing ` | tee /dev/fd/2` from the condition.

Tracing the git history, the earliest appearance of `| tee /dev/fd/2` can be found in https://github.com/kubernetes-sigs/kubeadm-dind-cluster/commit/07f6a8549b1fb52e568d248064d827847dd469fb#diff-6f53bfa951dee02d96a2466da8374ee8R408.

I wonder why it is needed and would there be a proper workaround.

**Comment by mrbobbytables** [comment]
Closing as this project is being deprecated and retired in favor of [KinD](https://github.com/kubernetes-sigs/kind).

Please see this issue for more details:
https://github.com/kubernetes/org/issues/1016

/close
