### ISSUE TITLE
Upgrade etcd version

### ISSUE THREAD

**Issue by tennix** [Mirantis/kubeadm-dind-cluster#36]
According to [kubeadm doc](https://kubernetes.io/docs/admin/kubeadm/#running-kubeadm-without-an-internet-connection), kubeadm uses etcd v3.0.17. But etcd image in mirantis/kubeadm-dind-cluster v1.6 and v1.7 is still v2.2.5. So could you upgrade etcd image to v3.0.17.
I didn't see how the save.tar.lz4 was created so I don't know how to upgrade this myself

**Comment by ivan4th** [comment]
That's actually an issue because storing old images in `save.tar.lz4` doesn't make sense, so thanks for reminding me about it. But note that kubeadm will still use newer images, it's just that they'll have to be pulled during the cluster setup.

**Comment by tennix** [comment]
Yep, kubeadm will use newer version nevertheless. But I wish the correct images are included in kubeadm-dind itself not wasting downloading images when cluster is setup.

**Comment by tennix** [comment]
I wonder why [here](https://github.com/Mirantis/kubeadm-dind-cluster/blob/master/build/funcs.sh#L25) is still a TODO, since kubeadm-dind-cluster already upgraded to v1.6 and v1.7 which uses etcd v3.0.17

**Comment by ivan4th** [comment]
Fixed by 1bf7caac8cdd72c866921d6852588fe573779456
Problem is, kubeadm deploy still causes 3 etcd images to be pulled: 2.2.1, 2.2.5 and 3.0.17. For now I included all of them, will try to investigate that separately
