### ISSUE TITLE
Fix hyperkube handling for k8s master (pre-1.8)

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/kubeadm-dind-cluster#39]
Current kubeadm no longer supports `KUBE_HYPERKUBE_IMAGE` and requires passing control plane image via the config.

**Comment by ivan4th** [comment]
Working on this issue, ETA is Monday Aug 28

**Comment by danehans** [comment]
@ivan4th any update on this issue?

**Comment by pmichali** [comment]
I've been working on trying to integrate IPv6 capabilities into kubeadm-dind-cluster, and have been hitting a bunch of issues with bringing up the cluster. @danehans pointed me to this issue and I was wondering if it is related to what I'm seeing, as I'm trying to use local source code repo for kubernetes.

If so, please let me know as soon as you have something for this. I'm glad to try out any proposed changes.

**Comment by pmichali** [comment]
Just to provide some background for the issue. It looks like DinD isn't working, when one wants to use a local kubernetes repo and run in "source" mode. From discussions with Ivan, it appears that KubeAdm no longer is accepting the KUBE_HYPERKUBE_IMAGE environment variable, which was the mechanism being used to allow local binaries to be used.

It sounds like the KubeAdm --config option needs to be used instead.

**Comment by danehans** [comment]
@ivan4th I found an issue with the fix-1.8+ branch. [This gist](https://gist.github.com/danehans/0d54a2b869229c3f95e4c2609507210d) details the issue and fix. In summary, the kdc deploy "almost" completes, it hangs on kube-proxy. The kube-proxy daemonset does not get deployed because the controller-manager pod is not running on the master container. The controller-manager pod on the master container is not running because the associated manifest is in /manifests.bak instead of /etc/kubernetes/manifests. I see that [snapshot](https://github.com/Mirantis/kubeadm-dind-cluster/blob/master/image/snapshot#L38-L49) is moving the manifest to /manifests.bak, but I don't understand the reasoning behind this code to update it as needed.

**Comment by danehans** [comment]
I also had to update `DefaultKubernetesVersion` to `v1.8.0-rc.1` in `cmd/kubeadm/app/apis/kubeadm/v1alpha1/defaults.go`. I need to understand how you manage the kubeadm.conf file so this k/v pair can be added or updated.

**Comment by danehans** [comment]
@ivan4th I still intermittently notice the kube-controllermanager.yaml static pod manifest not getting moved from the backup dir > /etc/kubernetes/manifests:

```
* Taking snapshot of the cluster 
deployment "kube-dns" scaled
deployment "kubernetes-dashboard" scaled
pod "kube-proxy-ztff7" deleted
WARNING: cluster glitch: proxy pods aren't removed; pods may 'blink' for some time after restore
* Waiting for kube-proxy and the nodes 
...................................................
```

After moving the manifest `# mv /manifests.bak/kube-controller-manager.yaml /etc/kubernetes/manifests/`:
```
* Waiting for kube-proxy and the nodes 
................................................................................................[done]
* Bringing up kube-dns and kubernetes-dashboard 
deployment "kube-dns" scaled
deployment "kubernetes-dashboard" scaled
.....[done]
NAME          STATUS         AGE       VERSION
kube-master   Ready,Master   4m        v1.9.0-alpha.1.609+a43cb7e2f363b8
kube-node-1   Ready          29s       v1.9.0-alpha.1.609+a43cb7e2f363b8
kube-node-2   Ready          29s       v1.9.0-alpha.1.609+a43cb7e2f363b8
* Access dashboard at: http://localhost:8899/ui

real	14m12.389s
user	0m49.801s
sys	0m14.597s
```

**Comment by pmichali** [comment]
@danehans In the PR I have (#42), I included a fix for that. The code just returns, if the controller or proxy pods cannot be stopped, and misses out out restoring the file. I changed the returns to breaks, as part of that PR and don't see that issue.

One one system, I do see a problem stopping DNS occasionally, but the system does come up, after a longer time.

**Comment by lukaszo** [comment]
1.8 and later versions work ok now
