### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by aramisjohnson** [Mirantis/kubeadm-dind-cluster#4]
So this worked like a charm, i booted an ubuntu container with DinD enabled on it, then i ran ./dind-cluster-v1.5.sh up. The cluster/node came up in a matter of minutes. I can docker exec into the newly created container/node and start issuing kubectl commands like normal.

The only problem is, if i dont docker exec into the container/node, kubectl commands return the following error;

The connection to the server localhost:8080 was refused - did you specify the right host or port?

How can I enable it so kubectl commands work on the parent container?

Again great job with this and any help you can provide will be much appreciated...

Ty

**Comment by ivan4th** [comment]
Sorry for delayed reply. Can you give some more details on your setup? Are you running the script from within a container?

**Comment by aramisjohnson** [comment]
this was my bad, it is working as expected, i am just new to containers, kubernetes, etc... thx

**Comment by ivan4th** [comment]
@aramisjohnson no problem! Please let me know if you have any other unexpected problems with `kubeadm-dind-cluster`.
