### ISSUE TITLE
Add IPv6 support to DinD

### ISSUE THREAD

**Issue by pmichali** [Mirantis/kubeadm-dind-cluster#41]
This is to track efforts to add support in DinD for Kubernetes cluster running in IPv6 mode (initially IPv6 only, later dualstack), connected to a IPv4 network. Goal is to be able to use DinD for E2E testing of IPv6 functionality in Kubernetes.

Note: IPv6 support in Kubernetes is a WIP, and as such, for now, custom Kubernetes repos are used that have patches/changes that are in-flight for kubernetes.

A DinD PR will be provided, based on the fix-1.8+ branch that is currently available (and based on the latest on master branch).

**Comment by lukaszo** [comment]
@pmichali can we close this issue or is there something more to be implemented?

**Comment by pmichali** [comment]
Yes, this has been completed some time ago.
