### ISSUE TITLE
Increasing dind worker nodes limit

### ISSUE THREAD

**Issue by Ruwan-Ranganath** [Mirantis/kubeadm-dind-cluster#59]
I'm trying to increase my worker nodes to 3 and currently there is 2. 
Couldn't find any workaround through the wiki.

**Comment by ivan4th** [comment]
Hi, try setting it via `export NUM_NODES=3` The config vars are described in [config.sh](https://github.com/Mirantis/kubeadm-dind-cluster/blob/master/config.sh)

**Comment by Ruwan-Ranganath** [comment]
Thanks and Worked .
