### ISSUE TITLE
How to enable RBAC on the cluster?

### ISSUE THREAD

**Issue by xenophenes** [Mirantis/kubeadm-dind-cluster#73]
I'm curious to know if it's possible to start the cluster with RBAC enabled, to allow for "--clusterrole" flag functionality and the like.

**Comment by MHBauer** [comment]
kubeadm sets up rbac by default. I've never had one of these without rbac.

**Comment by lukaszo** [comment]
RBAC is already enabled.

If you need something more please add a description and re open the issue.
