### ISSUE TITLE
can not provision dind-cluster on latest macOS with latest docker

### ISSUE THREAD

**Issue by redr0bin** [Mirantis/kubeadm-dind-cluster#86]
Hey,

I'm getting troubles launching dind-cluster for testing purposes. master is being provisioned but no nodes are active. Kubernetes 1.8.6 / macOS 10.13.3 / docker for mac 17.09.1 / 17.12.0

* Setting cluster config
Cluster "dind" set.
Context "dind" created.
Switched to context "dind".
* Starting node container: 1
* Starting DIND container: kube-node-1
* Node container started: 1
* Starting node container: 2
* Starting DIND container: kube-node-2
* Node container started: 2
mount: /lib/modules is not mountpoint or bad option

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

**Comment by djschny** [comment]
I'm getting the same thing as well with the v1.9 too.

**Comment by vicaya** [comment]
This is due the fixed version scripts not being updated by https://github.com/Mirantis/kubeadm-dind-cluster/commit/fc33b474f3a5e48940766c54e3d1b50a92f1c8b9

**Comment by pkrishn6** [comment]
@redr0bin : Does the suggested fix, fix the issue? I made the modification to the fixed script I use and I still see the issue...

**Comment by redr0bin** [comment]
Thanks for the info!
