### ISSUE TITLE
Insufficient memory

### ISSUE THREAD

**Issue by chlung** [Mirantis/kubeadm-dind-cluster#90]
Hi,
I deployed prometheus to k8s cluster, and pod failed to create with error "0/3 nodes are available: 1 PodToleratesNodeTaints, 3 Insufficient memory.".  The yaml files are from https://github.com/stefanprodan/k8s-prom-hpa/tree/master/prometheus.  Any suggestions about my error.

Thanks.

**Comment by pigmej** [comment]
it's not k-d-c error. It's error from kubernetes that says you that you don't have enough free memory in the cluster (2Gi for prometheus from your example).

**Comment by chlung** [comment]
@pigmej thanks.  Is possible to increase cluster memory in k-d-c?

**Comment by lukaszo** [comment]
@chlung dind does not set memory limits. It seems that your host machine has not enough memory
